base/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    
    path('room/<str:room_id>/',views.room, name= 'room'),
    
    path('create-room/',views.create_room, name = 'create-room'),
    path('update-room/<str:room_id>/',views.update_room, name = 'update-room'),
    path('delete-room/<str:room_id>/',views.delete_room, name = 'delete-room'),
    path('room-details/<str:room_id>/',views.room_details, name = 'room-details'),
    
    path('login/',views.login_page, name = 'login'),
    path('logout/',views.logout_page, name = 'logout'),
    path('register/',views.register_page, name = 'register'),

    path('delete-msg/<str:msg_id>/',views.delete_message, name = 'delete-msg'),
    path('profile/<str:user_id>/', views.user_profile, name = 'user-profile'),
    
    path('update-user/',views.update_profile, name = 'update-user'),
    path('comps/', views.comp_page, name = 'comps'),
    path('activity-page/', views.activity_page, name = 'activityPage'),
    path('activity/<str:user_id>', views.user_activity, name = 'user-activity'),
    path('following/', views.following, name = 'following'),

    path('profile/<str:recruiter_id>/followers/add', views.add_follower, name='add-follower'),
    path('profile/<str:recruiter_id>/followers/remove', views.remove_follower, name='remove-follower'),
    path('notifications/<str:not_id>', views.view_notifications, name = 'del-notification'),

    path('room/<str:room_id>/apply/', views.apply_now , name = 'apply'),
    path('application/<str:application_id>', views.update_application, name='update-application'),

    path('applications/', views.my_applications, name = 'myApplications'),
    path('room/<str:room_id>/applications/', views.view_applications, name = 'applications'),
    path('room/<job_id>/select-application/<can_id>/', views.select_application, name='select-application'),
    path('room/reject-application/<application_id>/', views.reject_application, name = 'reject-application'),
]

referred/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

# connect media root to media url
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

base/models.py
from django.db import models
from django.db.models.deletion import CASCADE
# for default User model
# from django.contrib.auth.models import User

#for custom user model
from django.contrib.auth.models import AbstractUser

from django.core.validators import FileExtensionValidator

class User(AbstractUser):
    name = models.CharField(max_length=150, help_text ='Enter your full name')
    
    email = models.EmailField(unique=True)

    username = models.CharField(max_length=100, unique=True)
    
    bio = models.TextField(null=True, blank=True)

    linkedin = models.URLField(unique = True,null=True, blank=True)

    avatar = models.ImageField(upload_to = 'images/', null=True, default="images/avatar.svg")

    followers = models.ManyToManyField("self",related_name = 'following', blank=True, symmetrical=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','name']
    
    def __str__(self):
        return str(self.name)
    

class Company(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name 

class Room(models.Model):
    recruiter = models.ForeignKey(User, on_delete=models.CASCADE, null=True) 
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null = True)
    position = models.CharField(max_length = 200)
    description = models.TextField()

    # The related_name attribute specifies the name of the reverse relation from the User model back to your model. 
    # If you don’t specify a related_name, Django automatically creates one using the name of your model with the suffix _set.

    # participants = models.ManyToManyField(User, related_name = 'participants' ,blank = True)
    total_applications = models.IntegerField(default=0)
    location = models.CharField(max_length=250, null=True, blank = True)

    skills = models.TextField(max_length = 150, blank=True, null= True, help_text ='Enter all the required skills each separated by commas. ex. Java, Python, Django')
    link = models.URLField(blank = True, null = True, help_text ='Link to the carrier page of company so if they want they can directly apply there')
    experience = models.CharField(max_length = 100, blank = True, null = True)
    updated = models.DateTimeField(auto_now = True) #every time we save 
    created = models.DateTimeField(auto_now_add = True) # at first time we created / instance was created

    #for ordering objects of room by created or updated value
    class Meta:
        ordering = ['-updated', '-created']
    
    def __str__(self):
        return self.position 

class Message(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now = True) #every time we save 
    created = models.DateTimeField(auto_now_add = True) # at first time we created / instance was created

    class Meta:
        ordering = ['-updated', '-created']
    
    def __str__(self):
        if len(self.body) > 60:
            return self.body[:60] + '.....'
        return self.body

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    notification_type = models.CharField(max_length = 20,choices = (('room', 'Room creation'),('selected','Selected for refferal')),default = 'room') 

    def __str__(self):
        return self.user
    
class Application(models.Model):

    applicant = models.ForeignKey(User, on_delete=models.CASCADE)

    opportunity = models.ForeignKey(Room, on_delete=models.CASCADE)

    resume  = models.FileField(upload_to = 'pdfs/', validators=[FileExtensionValidator(allowed_extensions=["pdf"])], help_text='upload pdf file only')

    applied = models.DateTimeField(auto_now_add = True)

    experience = models.CharField(max_length = 100, blank = True, null = True)

    def __str__(self):
        return self.applicant.name

class Selected(models.Model):
    
    applicant = models.ForeignKey(User, on_delete=models.CASCADE)

    opportunity = models.ForeignKey(Room, on_delete=models.CASCADE)

    resume  = models.FileField()

    applied = models.DateTimeField()

    experience = models.CharField(max_length = 100, blank = True, null = True)

    def __str__(self):
        return self.applicant.name 

base/forms.py
from django.forms import ModelForm
from .models import Room, User, Application

from django.contrib.auth.forms import UserCreationForm 
from django import forms


class RoomForm(ModelForm):
    class Meta:
        model = Room
        # fields = '__all__' if you want to include all fields in the form
        fields = '__all__' 
        exclude = ['recruiter']


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2'] #1 and 2 for password confirmation

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'linkedin', 'bio']

class ApplicationForm(ModelForm):
    class Meta:
        model = Application
        fields = ['resume', 'experience']

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Room, Company, Message, User, Notification, Application, Selected
from .forms import RoomForm, UserForm, MyUserCreationForm, ApplicationForm

from django.db.models import Count

#for default user model
# from django.contrib.auth.models import User

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from django.contrib.auth.forms import UserCreationForm 


#decorators
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator

#for query
from django.db.models import Q

import json

# Create your views here.

def login_page(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            users = User.objects.get(email=email)
        except:
            messages.error(request, 'User does not exist')

            return render(request, 'base/login-register.html', {'page':page})

        user = authenticate(request, email = email, password = password)

        if user is not None:
            login(request, user)

            return redirect('home')
        
        else:
            messages.error(request, 'Username or password is incorrect')

    context = {
        'page': page
    }
    return render(request,'base/login-register.html', context)

def logout_page(request):
    logout(request) #this will delete the user /the token of perticular session which keeps user logged in
    return redirect('home')

def register_page(request):
    page = 'register'

    form = MyUserCreationForm()
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():

            #form.cleaned_data['username'] :- If you want to access any perticular data from the form
            #form.data['username'] :- will return in html tag so better to use cleaned_data

            user = form.save(commit=False)  # do not save the user into the database

            user.username = user.username.lower()

            user.save()
            # user = authenticate(username=username, password=raw_password) 
            login(request, user)

            return redirect('home')
        
        else:
            if form.has_error('username'):
                messages.error(request,'user with this username already exists')
            elif form.has_error('password1'):
                messages.error(request,'Password is too week!!!')
            elif form.has_error('password2'):
                messages.error(request, 'Password entred in both fields are not matching!!')
    
    context = {
        'page': page,
        'form': form
    }
    return render(request,'base/login-register.html', context)

def home(request):

    q = request.GET.get('q') if request.GET.get('q') != None else ''

    #so first it will query the compay with name equals to the value of q and pass to upar flow which means to Room : ex. company__name == company.name
    # rooms = Room.objects.filter(company__name = q)

    #check if name contains specific value given in q or make q == '' if q is not there in the url and when q is '' then it will display all the values
    rooms = Room.objects.filter(
        Q(company__name__icontains = q) |
        Q(position__icontains = q) 
    )

    room_messages = Message.objects.filter(
        Q(room__company__name__icontains=q) | 
        Q(room__position__icontains=q))[0:5]

    room_count = rooms.count()

    paginator = Paginator(rooms, 5)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)

    # order the company by most number of rooms in descending order
    companies = Company.objects.annotate(num_room=Count("room")).order_by("-num_room")[:5]
    # companies = Company.objects.all()[0:5]

    notifications = []
    notification_number = 0
    if request.user.is_authenticated:
        notifications = Notification.objects.filter(user=request.user)
        notification_number = len(notifications)

    context = {
        'rooms':page_obj,
        'companies':companies,
        'room_count':room_count,
        'room_msgs':room_messages,
        'notifications':notifications,
        'notification_number':notification_number
    }
    return render(request, 'base/home.html', context)

@login_required(login_url = 'login')
def room(request, room_id):
    
    room = Room.objects.get(id=room_id)
    
    # to get the message (child object) get particular parent object from them get all the childer of that parent object
    #  by using the class name in small_set.all() method
    #for Many to one relationship _set
    room_messages = room.message_set.all().order_by('-created')

    notifications = []
    if request.user.is_authenticated:
        notifications = Notification.objects.filter(user=request.user)
        notification_number = len(notifications)
    
    #for many to many relationship no need to use _set
    # participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user = request.user,
            room = room,
            body = request.POST.get('body')
        )

        # room.participants.add(request.user)

        # here other parameters are query parameters :- GET request parameters
        return redirect('room',room_id = room.id)

    applications = Application.objects.filter(opportunity_id = room_id)

    try:
        user_application = applications.get(applicant_id = request.user.id)
    except Application.DoesNotExist:
        user_application = None

    already_applied = False
    if user_application is not None:
        already_applied = True
       
    already_selected = Selected.objects.filter(applicant_id=request.user.id).filter(opportunity_id = room_id).exists()
    
    note = ''
    if already_applied:
        note = 'Already applied!!'
    elif already_selected:
        note = 'Congratulations!! Your application is selected for referral'
    
    not_applied = not (already_applied or already_selected)

    skill_set = set()

    if room.skills:
        skills = room.skills.split(',')
        for skill in skills:
            s=skill.strip()
            skill_set.add(s)

    context = {
        'room': room,
        'room_msgs': room_messages,
        # 'participants': participants,
        'notifications':notifications,
        'notification_number':notification_number,
        'not_applied': not_applied,
        'already_applied': already_applied,
        'user_application': user_application,
        'note': note,
        'skills': skill_set
    }

    return render(request, 'base/room.html', context)

def room_details(request, room_id):
    room = Room.objects.get(id=room_id)
    skill_set = set()

    if room.skills :
        skills = room.skills.split(',')
        for skill in skills:
            s=skill.strip()
            skill_set.add(s)
    return render(request, 'base/room-detailspage.html', {'room': room, 'skills': skill_set})


#the below decorator will make sure that this function is called only if user is logged in
# and if user is not logged in it will redirect to login page
@login_required(login_url='login')
def create_room(request):
    companies = Company.objects.all()
    form = RoomForm()
    if request.method == 'POST':
        company_name = request.POST.get('company')
        
        company, created = Company.objects.get_or_create(name = company_name) 

        room = Room.objects.create(
            position = request.POST.get('position'),
            company = company,
            recruiter = request.user,
            description = request.POST.get('description'),
            skills = request.POST.get('skills'),
            experience = request.POST.get('experience'),
            location = request.POST.get('location'),
            link = request.POST.get('link'),
            total_applications = 0
        )
        # line 159 to 165 implementation using the form 
        # form = RoomForm(request.POST)
        # if form.is_valid():
        #     room = form.save(commit=False) It helps to get model(room) object based on form data

        #     room.recruiter = request.user
            
        #     room.save()

        # return redirect('home')  redirect : here home is taken form name in urls.py of base app
        return redirect('room', room.id)

    # print(companies)
    context = {'form' : form , 'list_companies':companies ,'create': True}
    
    return render(request, 'base/room-form.html', context)

@login_required(login_url='login')
def update_room(request, room_id):
    room = Room.objects.get(id=room_id)

    companies = Company.objects.all()

    form = RoomForm(instance = room)

    if request.user != room.recruiter :
        return HttpResponse('You are not allowed to update this room')

    if request.method == 'POST':
        company_name = request.POST.get('company')
        
        company, created = Company.objects.get_or_create(name = company_name) 

        room.position = request.POST.get('position')
        room.company = company
        room.description = request.POST.get('description')
        room.skills = request.POST.get('skills')
        room.experience = request.POST.get('experience')
        room.location = request.POST.get('location')
        room.link = request.POST.get('link')
        
        room.save()
        return redirect('room',room_id)

    # if RoomForm() -> then it will return empty instance but we can initialize it using room so that while calling update the form is not empty 
    # form = RoomForm(instance = room)
    
    # if request.user != room.recruiter :
    #     return HttpResponse('You are not allowed to update this room')

base/templates/base/activity-page.html
{% extends 'main_no_navbar.html' %}

{% block content %}
<main class="activity layout">
  <div class="container--2">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Recent Activities</h3>
        </div>
      </div>

      <div class="activities-page layout__body">

        {% for message in room_msgs %}
        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="{{ message.user.avatar.url }}" />
              </div>
              <p style="color: black;">
                @{{message.user.username }}
                <span>{{message.created|timesince}} ago</span>
              </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete-msg' message.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                  </path>
                </svg>
              </a>
            </div>
            {% endif %}

          </div>
          <div class="activities__boxContent">
            <p style="color:rgb(38, 101, 218);">replied to post “<a style="color: var(--color-dark);" href="{% url 'room' message.room.id %}">{{message.room}} : {{message.room.company}}</a>”</p>
            <div class="activities__boxRoomContent">
              {{message}}
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>
</main>
{% endblock %}

base/templates/base/companies-page.html
{% extends 'main_no_navbar.html' %}

{% block content%}
    <main class="company layout">
      <div class="container--2">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Companies</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search" method="GET" action="">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name='q' placeholder="Search for Companies" />
              </label>
            </form>

            <ul class="topics__list">
              
              <li>
                <a href="{% url 'comps' %}" class="active">All</a>
              </li>
              
              {% for comp in comps%}
              <li>
                <a href="{% url 'home' %}?q={{comp.name}}" class="active">{{comp.name}}<span>{{comp.room_set.all.count}}</span></a>
              </li>
              {% endfor %}
              
            </ul>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

base/templates/base/company.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Companies</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'home' %}" class="active">All </a>
      </li>
      {% for comp in companies %}
        <li>
        <a href="{% url 'home' %}?q={{comp.name}}">{{comp}}<span>{{comp.room_set.all.count}}</span></a>
        </li>
      {% endfor %}
    </ul>
    <a class="btn btn--link" href="{% url 'comps' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>

base/templates/base/delete.html
{% extends 'main_no_navbar.html' %}

{% block content %}
    <main class="delete-item layout">
        <div class="container--2">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        
                        <div class="form__group" style="color: var(--color-dark);">
                            <p>Are you sure want to delete this "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="script.js"></script>
{% endblock %}

base/templates/base/edit-user.html
{% extends 'main_no_navbar.html' %}
{% block content %}
    <main class="update-account layout">
        <div class="container--2">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'user-profile' request.user.id %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <!-- <form class="form" action="" method="POST"> -->
                    <form class="form" action="" method="POST" enctype="multipart/form-data"> <!-- for sending files through post request   -->
                      {% csrf_token %}
                        {% for field in form%}
                        <div class="form__group">
                            <label>{{field.label}}</label>
                            {{field}}
                        </div>
                        {% endfor %}

                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'user-profile' request.user.id %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
{% endblock %}

base/templates/base/feed.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'user-profile' room.recruiter.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{room.recruiter.avatar.url}}" />
        </div>
        <span style="color : #000;">@ {{room.recruiter.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{ room.created|timesince }} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'room' room.id %}">{{room.position}}</a>
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path fill="#248AFD" d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
          </path>
          <path fill="#248AFD" d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
          </path>
          <path fill="#248AFD" d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
          </path>
          <path fill="#248AFD" d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
          </path>
        </svg>
        <!-- {{room.participants.all.count}} Joined -->
        {{room.total_applications}} Applied
      </a>
      <p class="roomListRoom__topic">{{room.company.name}}</p>
    </div>
  </div>
{% endfor %}

<div class="div_top_hypers">
<ul class="ul_top_hypers">
  {% if rooms.has_previous %}
      <li class="page-item">
      <a class="page-link" href="?page={{ rooms.previous_page_number }}"><span>< Previous</span></a>
    </li>
  {% endif %}

  {% if rooms.number|add:'-4' > 1 %}
      <li class="page-item"><a class="page-link" href="?page={{ rooms.number|add:'-5' }}"><span>&hellip;</span></a></li>
  {% endif %}

  {% for i in rooms.paginator.page_range %}
      {% if rooms.number == i %}
          <!-- <li class="page-item active" aria-current="page"> -->
        <!-- <span class="page-link">
          {{ i }}
          <span class="sr-only">(current)</span> 
          
        </span> -->
        <li class="page-item"><span style="color:#fff">{{i}}</span></li>
      <!-- </li> -->
      {% elif i > rooms.number|add:'-5' and i < rooms.number|add:'5' %}
           <li class="page-item"><a class="page-link" href="?page={{ i }}"><span>{{i}}</span></a></li>
      {% endif %}
  {% endfor %}

  {% if rooms.paginator.num_pages > rooms.number|add:'4' %}
     <li class="page-item"><a class="page-link" href="?page={{ rooms.number|add:'5' }}"><span>&hellip;</span></a></li>
  {% endif %}

  {% if rooms.has_next %}
      <li class="page-item">
      <a class="page-link" href="?page={{ rooms.next_page_number }}"><span>Next ></span></a>
    </li>
  {% endif %}
</ul>
</div>